-- ============================================================================
-- Cartiae Rae — Private eBook Storage Foundation
-- Migration: 20260723_03_ebooks_storage.sql
--
-- Run THIRD, after:
--   20260723_01_admin_users_simplify.sql  (adds admin_users.is_active)
--   20260723_02_orders_schema.sql         (orders + order_items)
--
-- Run in: Supabase Dashboard → SQL Editor
--
-- Creates:
--   • Private 'ebooks' Storage bucket
--   • public.ebook_assets table
--   • Versioning constraints (unique per ebook+version; one active per ebook)
--   • RLS policies on ebook_assets
--   • Storage object policies on the ebooks bucket
--   • Dedicated trigger: public.set_ebook_assets_updated_at()
--   • Indexes for entitlement lookup, ordering, and integrity checks
--
-- Safe to re-run: uses IF NOT EXISTS / ON CONFLICT DO NOTHING throughout.
-- No generic trigger function is touched or replaced.
-- No service-role key appears in this file.
-- No signed URLs are stored in the database.
-- No public-read policies are created.
-- ============================================================================


-- ============================================================================
-- DESIGN DECISIONS
-- ============================================================================
--
-- 1. Asset ownership model
--    ─────────────────────
--    EBook.id (text, e.g. "ebook-001")
--      → ebook_assets.ebook_id         (entitlement bridge)
--      → ebook_assets.storage_path     (resolved at delivery time)
--      → signed URL (generated by service-role client, never stored)
--
--    order_items.product_id proves purchase entitlement.
--    The download function (Step 4) queries:
--      1. Verify paid order contains product_id = $ebookId, item_type = 'ebook'
--      2. SELECT storage_path FROM ebook_assets
--             WHERE ebook_id = $ebookId AND is_active = true
--      3. storage.from('ebooks').createSignedUrl(storage_path, 3600)
--
-- 2. Versioning
--    ──────────
--    Each row is an immutable version record. Old rows are never deleted;
--    is_active = false marks superseded versions. At most one row per ebook_id
--    may have is_active = true at any given time (enforced by partial unique
--    index). An eBook may temporarily have zero active assets during PDF
--    replacement or after an upload failure — this is intentional and
--    desirable for safe failure recovery. Version numbers are sequential (1, 2…).
--
-- 3. MIME type constraint extensibility
--    ─────────────────────────────────
--    The CHECK constraint currently allows only 'application/pdf'.
--    Adding EPUB later requires one ALTER TABLE migration to drop and
--    redefine the constraint — no table rebuild, no data loss. The
--    storage bucket's allowed_mime_types must also be updated at that time.
--
-- 4. Storage bucket conflict strategy
--    ──────────────────────────────────
--    This migration uses ON CONFLICT DO NOTHING for bucket creation.
--    Rationale: if the bucket already exists in production with different
--    settings, silently overriding those settings could break uploads that
--    are already working. The DO NOTHING approach preserves existing state
--    and a notice block reports which path was taken. If the bucket is new,
--    it is created with the correct private configuration.
--    If the bucket pre-exists with wrong settings, update it manually after
--    inspecting the current configuration in the Supabase dashboard.
--
-- 5. Object path convention
--    ─────────────────────────
--    Canonical path format (generated by the admin uploader in Step 2B):
--      {ebook_id}/v{version}/{sanitized-file-name}.pdf
--    Example:
--      ebook-001/v1/4c-hair-growth-guide.pdf
--
--    Rules enforced by the uploader (not enforceable in SQL):
--      • No customer PII in the path
--      • No order IDs in the path
--      • File name sanitized: lowercase, spaces → hyphens, max 80 chars
--      • Only .pdf extension for MIME type application/pdf
--
-- 6. Checksum
--    ─────────
--    checksum_sha256 is nullable in Step 2A.
--    Step 2B (admin uploader) will compute SHA-256 via the browser's
--    SubtleCrypto API before upload, then store the hex digest here.
--    Supports: duplicate detection, integrity verification, version diffing.
--    No checksum computation occurs in SQL.
-- ============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
-- 0. Dependency guard
--    Aborts if admin_users.is_active is missing (migration 01 not applied).
-- ─────────────────────────────────────────────────────────────────────────────
do $$
begin
  if not exists (
    select 1
    from   information_schema.columns
    where  table_schema = 'public'
      and  table_name   = 'admin_users'
      and  column_name  = 'is_active'
  ) then
    raise exception
      'DEPENDENCY MISSING: admin_users.is_active not found. '
      'Run 20260723_01_admin_users_simplify.sql first.';
  end if;
  raise notice 'Dependency check passed: admin_users.is_active exists.';
end $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Private 'ebooks' Storage bucket
--
--    ON CONFLICT DO NOTHING preserves any existing bucket configuration.
--    The notice block reports whether the bucket was newly created or
--    already present. If already present with wrong settings, inspect
--    the Supabase dashboard and update manually.
-- ─────────────────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'ebooks',
  'ebooks',
  false,             -- PRIVATE: no public read
  52428800,          -- 50 MB per file
  array['application/pdf']
)
on conflict (id) do nothing;

-- Validate effective bucket configuration — abort if insecure or misconfigured.
-- ON CONFLICT DO NOTHING preserves any pre-existing bucket. This block
-- ensures that whatever configuration is now in effect satisfies the required
-- security posture. A public ebooks bucket or unexpected MIME/size settings
-- are hard aborts: they cannot be silently accepted for a private digital-
-- product delivery system.
do $$
declare
  v_public           boolean;
  v_file_size_limit  bigint;
  v_mime_types       text[];
begin
  select public, file_size_limit, allowed_mime_types
  into   v_public, v_file_size_limit, v_mime_types
  from   storage.buckets
  where  id = 'ebooks';

  if not found then
    raise exception
      'The ebooks storage bucket was not created and does not exist. '
      'Investigate storage.buckets permissions.';
  end if;

  raise notice 'ebooks bucket state: public=%, file_size_limit=%, allowed_mime_types=%',
    v_public, v_file_size_limit, v_mime_types;

  if v_public is distinct from false then
    raise exception
      'The ebooks bucket exists but is marked PUBLIC. eBook files must not be '
      'publicly readable. Correct before continuing: '
      'UPDATE storage.buckets SET public = false WHERE id = ''ebooks'';';
  end if;

  if v_file_size_limit is distinct from 52428800 then
    raise exception
      'The ebooks bucket has an unexpected file_size_limit: %. '
      'Expected 52428800 (50 MB). Review and update before continuing.',
      v_file_size_limit;
  end if;

  if v_mime_types is null
     or not ('application/pdf' = any(v_mime_types)) then
    raise exception
      'The ebooks bucket does not permit application/pdf in allowed_mime_types. '
      'Current value: %.', v_mime_types;
  end if;

  raise notice 'ebooks bucket security validation passed.';
end $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Storage object policies — ebooks bucket
--
--    All policies are scoped to bucket_id = 'ebooks'.
--    Only the active authenticated admin may read, insert, update, or delete.
--    Anonymous users have no access.
--    All other authenticated users have no access.
--    The service-role client (used by Netlify Functions for signed URL
--    generation) bypasses RLS automatically — no policy needed for it.
-- ─────────────────────────────────────────────────────────────────────────────

-- Admin: read object metadata (needed to list uploaded assets in the portal)
drop policy if exists "ebook storage admin select" on storage.objects;
create policy "ebook storage admin select"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'ebooks'
    and exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  );

-- Admin: upload new objects
drop policy if exists "ebook storage admin insert" on storage.objects;
create policy "ebook storage admin insert"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'ebooks'
    and exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  );

-- Admin: replace / overwrite objects (needed for re-upload of same path).
-- WITH CHECK is required alongside USING to prevent an update from mutating
-- the object's bucket_id to a different bucket.
drop policy if exists "ebook storage admin update" on storage.objects;
create policy "ebook storage admin update"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'ebooks'
    and exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  )
  with check (
    bucket_id = 'ebooks'
    and exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  );

-- Admin: delete obsolete storage objects (e.g. after deactivating an asset)
drop policy if exists "ebook storage admin delete" on storage.objects;
create policy "ebook storage admin delete"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'ebooks'
    and exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  );


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. ebook_assets table
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists public.ebook_assets (

  id   uuid primary key default gen_random_uuid(),

  -- ── eBook reference ───────────────────────────────────────────────────────
  -- Matches EBook.id and order_items.product_id (nanoid-style text, not UUID).
  -- Not a FK yet — eBooks are still in localStorage (Step 6 will add the FK
  -- when the ebooks catalog is migrated to Supabase).
  ebook_id text not null
    constraint ebook_assets_ebook_id_nonempty check (ebook_id <> ''),

  -- ── Storage reference ─────────────────────────────────────────────────────
  -- bucket is always 'ebooks'; enforced by check constraint.
  storage_bucket text not null default 'ebooks'
    constraint ebook_assets_bucket_check check (storage_bucket = 'ebooks'),

  -- Path within the ebooks bucket.
  -- Convention: {ebook_id}/v{version}/{sanitized-file-name}.pdf
  -- Generated by the admin uploader; users cannot provide arbitrary paths.
  storage_path text not null
    constraint ebook_assets_path_nonempty check (storage_path <> ''),

  -- ── Versioning ────────────────────────────────────────────────────────────
  -- Sequential per ebook_id (1, 2, 3…). Enforced by unique constraint below.
  version integer not null default 1
    constraint ebook_assets_version_positive check (version > 0),

  -- ── File metadata ─────────────────────────────────────────────────────────
  file_name text not null
    constraint ebook_assets_filename_nonempty check (file_name <> ''),

  -- Currently: application/pdf only.
  -- To add EPUB later: ALTER TABLE DROP CONSTRAINT, ADD CONSTRAINT with new list.
  -- No table rebuild required. Also update storage bucket allowed_mime_types.
  mime_type text not null
    constraint ebook_assets_mime_type_check
      check (mime_type in ('application/pdf')),

  -- Integer bytes; never float. NULL is not permitted.
  size_bytes bigint not null
    constraint ebook_assets_size_nonneg check (size_bytes >= 0),

  -- SHA-256 hex digest — nullable in Step 2A; populated by Step 2B uploader.
  -- Must be a 64-character lowercase hex string when present.
  -- Supports: duplicate detection, integrity verification, version diffing.
  -- Step 2B must store lowercase hex consistently (SubtleCrypto digest → hex).
  checksum_sha256 text
    constraint ebook_assets_checksum_format
      check (
        checksum_sha256 is null
        or checksum_sha256 ~ '^[a-f0-9]{64}$'
      ),

  -- ── Asset state ───────────────────────────────────────────────────────────
  -- Only one row per ebook_id may be active (partial unique index below).
  -- Old rows are retained for history; is_active = false marks them inactive.
  is_active boolean not null default true,

  -- ── Audit ─────────────────────────────────────────────────────────────────
  -- created_by: the Supabase Auth UID of the admin who uploaded this version.
  -- SET NULL on user deletion preserves the asset row for historical record.
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ── Uniqueness constraints ────────────────────────────────────────────────────

-- Each ebook may have version 1, 2, 3… but not two rows with the same version.
alter table public.ebook_assets
  add constraint if not exists ebook_assets_version_unique
    unique (ebook_id, version);

-- Each storage object may be referenced by at most one asset row.
-- Prevents accidental aliasing and aids orphan detection during cleanup.
alter table public.ebook_assets
  add constraint if not exists ebook_assets_storage_path_unique
    unique (storage_path);

-- At most one active asset per eBook at any given time.
-- (Not "exactly one" — an eBook may temporarily have zero active assets
-- during PDF replacement or after upload failure. That is intentional.)
-- Deactivate the current row before inserting a replacement version.
-- Historical rows (is_active = false) are excluded from this index.
create unique index if not exists ebook_assets_one_active_per_ebook
  on public.ebook_assets (ebook_id)
  where is_active = true;

-- RLS
alter table public.ebook_assets enable row level security;


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Updated-at trigger — table-specific, no shared function touched
-- ─────────────────────────────────────────────────────────────────────────────
create or replace function public.set_ebook_assets_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ebook_assets_set_updated_at on public.ebook_assets;
create trigger ebook_assets_set_updated_at
  before update on public.ebook_assets
  for each row execute function public.set_ebook_assets_updated_at();


-- ─────────────────────────────────────────────────────────────────────────────
-- 5. RLS Policies on ebook_assets
--
--    All policies verify the active-admin condition.
--    Service-role client bypasses RLS automatically.
--    No anonymous access. No general authenticated-user access.
--    No DELETE policy — deactivate rows via is_active = false instead.
--    If an explicit hard-delete is ever needed, add a policy then.
-- ─────────────────────────────────────────────────────────────────────────────

-- Active admin may read all asset rows (needed for portal asset listing)
drop policy if exists "ebook_assets admin select" on public.ebook_assets;
create policy "ebook_assets admin select"
  on public.ebook_assets
  for select
  to authenticated
  using (
    exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  );

-- Active admin may insert new asset records
drop policy if exists "ebook_assets admin insert" on public.ebook_assets;
create policy "ebook_assets admin insert"
  on public.ebook_assets
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  );

-- Active admin may update asset records (e.g. set is_active = false, add checksum)
-- USING: must be an active admin to target the row
-- WITH CHECK: must remain an active admin after the update
drop policy if exists "ebook_assets admin update" on public.ebook_assets;
create policy "ebook_assets admin update"
  on public.ebook_assets
  for update
  to authenticated
  using (
    exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  )
  with check (
    exists (
      select 1
      from   public.admin_users au
      where  au.id        = auth.uid()
        and  au.is_active = true
    )
  );


-- ─────────────────────────────────────────────────────────────────────────────
-- 6. Indexes
-- ─────────────────────────────────────────────────────────────────────────────

-- Primary lookup: all assets for a given ebook (version history list)
create index if not exists ebook_assets_ebook_id_idx
  on public.ebook_assets (ebook_id);

-- Admin portal ordering: most recently uploaded first
create index if not exists ebook_assets_created_at_idx
  on public.ebook_assets (created_at desc);

-- Integrity: look up an asset by its storage path (e.g. to detect orphaned objects).
-- Also serves lookups by storage_path for the unique constraint above.
create index if not exists ebook_assets_storage_path_idx
  on public.ebook_assets (storage_path);

-- Notes on indexes not added:
--   is_active alone: a Boolean index over a mostly-true column is low-value
--     and provides no selectivity improvement. The partial unique index
--     ebook_assets_one_active_per_ebook already covers the principal
--     active-asset lookup (WHERE ebook_id = $x AND is_active = true).
--   (ebook_id, is_active): redundant with the partial unique index above.


-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Verification queries — run after applying to confirm structure
-- ─────────────────────────────────────────────────────────────────────────────

-- Bucket configuration
select id, name, public, file_size_limit, allowed_mime_types
from   storage.buckets
where  id = 'ebooks';

-- Table columns
select column_name, data_type, is_nullable, column_default
from   information_schema.columns
where  table_schema = 'public'
  and  table_name   = 'ebook_assets'
order by ordinal_position;

-- Constraints
select conname, contype, pg_get_constraintdef(oid) as definition
from   pg_constraint
where  conrelid = 'public.ebook_assets'::regclass
order by conname;

-- Indexes
select indexname, indexdef
from   pg_indexes
where  schemaname = 'public'
  and  tablename  = 'ebook_assets'
order by indexname;

-- RLS policies on ebook_assets
select policyname, cmd, roles, qual, with_check
from   pg_policies
where  schemaname = 'public'
  and  tablename  = 'ebook_assets'
order by policyname;

-- Storage policies on storage.objects (ebooks bucket)
-- Uses the canonical pg_policies catalog rather than the Supabase-specific
-- storage.policies view, which is not portable across all Postgres environments.
select policyname, cmd, roles, qual, with_check
from   pg_policies
where  schemaname = 'storage'
  and  tablename  = 'objects'
order by policyname;

-- Trigger function
select routine_name, routine_type
from   information_schema.routines
where  routine_schema = 'public'
  and  routine_name   = 'set_ebook_assets_updated_at';
