-- ============================================================================
-- Cartiae Rae — Orders + secure eBook delivery
-- ============================================================================
-- Run this in the Supabase SQL editor (Dashboard -> SQL -> New query).
--
-- Creates:
--   1. public.ebook_files  — maps an eBook id to its object path in the private
--                            "ebooks" storage bucket. This is the ONLY source of
--                            truth for which file an order may download, so a
--                            buyer can never request an arbitrary path.
--   2. storage bucket "ebooks" — PRIVATE. No public read policy is created, so
--                            files are reachable only through a short-lived
--                            signed URL minted by get-ebook-download.
--
-- NOTE: public.orders and public.order_items are NOT touched here. They already
-- existed with a complete schema; see orders_schema_cleanup.sql.
--
-- ebook_files has RLS enabled with NO policies: the anon/authenticated keys can
-- read nothing. The Netlify functions use the service_role key, which bypasses
-- RLS by design.
-- ============================================================================

-- ── 2) eBook id -> storage path mapping ─────────────────────────────────────
create table if not exists public.ebook_files (
  ebook_id     text primary key,
  storage_path text not null,   -- path inside the private "ebooks" bucket
  title        text,
  created_at   timestamptz not null default now()
);

-- Same repair as above, in case this table also predates this script.
alter table public.ebook_files add column if not exists storage_path text;
alter table public.ebook_files add column if not exists title        text;
alter table public.ebook_files add column if not exists created_at   timestamptz default now();

alter table public.ebook_files enable row level security;
-- Again: no policies. Only the service_role key may read this.

-- Seed the three eBooks currently in src/data/initialData.ts.
-- The ebook_id MUST match the cart item id exactly ('ebook-1', not 'eb1') —
-- get-ebook-download looks these up by the id stored on the order.
-- Upload the matching PDFs to the "ebooks" bucket under these exact paths.
insert into public.ebook_files (ebook_id, storage_path, title) values
  ('ebook-1', '4c_growth_blueprint_cartiae_rae.pdf', 'The 4C Growth Blueprint'),
  ('ebook-2', 'wash_day_mastery_cartiae_rae.pdf',    'Wash Day Mastery'),
  ('ebook-3', 'protective_styles_playbook.pdf',      'The Protective Style Playbook')
on conflict (ebook_id) do update
  set storage_path = excluded.storage_path,
      title        = excluded.title;

-- ── 3) Private "ebooks" storage bucket ──────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('ebooks', 'ebooks', false, 104857600, array['application/pdf', 'application/epub+zip'])
on conflict (id) do update
  set public             = false,          -- force private even if it existed as public
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Remove any policy that would expose the bucket publicly.
drop policy if exists "ebooks public read"   on storage.objects;
drop policy if exists "ebooks public insert" on storage.objects;

-- Signed-in admins may upload/replace eBook files from the admin portal.
drop policy if exists "ebooks auth insert" on storage.objects;
create policy "ebooks auth insert"
  on storage.objects for insert to authenticated
  with check ( bucket_id = 'ebooks' );

drop policy if exists "ebooks auth update" on storage.objects;
create policy "ebooks auth update"
  on storage.objects for update to authenticated
  using ( bucket_id = 'ebooks' );

drop policy if exists "ebooks auth delete" on storage.objects;
create policy "ebooks auth delete"
  on storage.objects for delete to authenticated
  using ( bucket_id = 'ebooks' );

-- NOTE: no SELECT policy is granted on the ebooks bucket. Reads happen only via
-- the signed URLs generated by the get-ebook-download function.

-- ── Confirm ────────────────────────────────────────────────────────────────
select ebook_id, storage_path, title from public.ebook_files order by ebook_id;
