-- =========================================================================
-- Cartiae Rae Hair Studio - Supabase Database Schema DDL
-- Execute these statements in the Supabase SQL Editor to bootstrap Phase 1
-- =========================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- 1. ADMIN PROFILES TABLE (admin_users)
-- ────────────────────────────────────────────────────────────────────────────
-- Stores staff authorization details and role scopes linked to Supabase Auth.

CREATE TABLE IF NOT EXISTS public.admin_users (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL CHECK (role IN ('super_admin', 'store_manager', 'content_manager')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row-Level Security (RLS)
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- RLS Policies for admin_users
CREATE POLICY "Allow users to view their own profile"
  ON public.admin_users
  FOR SELECT
  TO authenticated
  USING (auth.uid() = id);

CREATE POLICY "Allow super_admins to manage all profiles"
  ON public.admin_users
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE admin_users.id = auth.uid() AND admin_users.role = 'super_admin'
    )
  );

-- ────────────────────────────────────────────────────────────────────────────
-- 2. CONTACT REQUESTS TABLE (contact_requests)
-- ────────────────────────────────────────────────────────────────────────────
-- Stores visitor inquiries sent from the public Contact page.

CREATE TABLE IF NOT EXISTS public.contact_requests (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  subject TEXT,
  message TEXT NOT NULL,
  porosity TEXT,
  photo_attachment TEXT,
  status TEXT NOT NULL CHECK (status IN ('Pending', 'Responded', 'Read', 'Archived')),
  date TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row-Level Security (RLS)
ALTER TABLE public.contact_requests ENABLE ROW LEVEL SECURITY;

-- RLS Policies for contact_requests
-- 1. Anyone (including anonymous visitors) can insert submissions
CREATE POLICY "Allow public submissions"
  ON public.contact_requests
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- 2. Authenticated administrative users can read all contact requests
CREATE POLICY "Allow admins to read inquiries"
  ON public.contact_requests
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE admin_users.id = auth.uid()
    )
  );

-- 3. Authenticated administrative users can update contact request statuses
CREATE POLICY "Allow admins to update inquiries"
  ON public.contact_requests
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE admin_users.id = auth.uid()
    )
  );

-- 4. Authenticated administrative users can delete contact requests
CREATE POLICY "Allow admins to delete inquiries"
  ON public.contact_requests
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.admin_users
      WHERE admin_users.id = auth.uid()
    )
  );

-- ────────────────────────────────────────────────────────────────────────────
-- 3. SEEDING & SETUP INSTRUCTIONS
-- ────────────────────────────────────────────────────────────────────────────

/*
-- STEP A: Create admin credentials in Auth -> Users in the Supabase Dashboard
-- E.g., email: 'admin@cartiaerae.com', password: 'some_strong_password'

-- STEP B: Copy the User ID (UUID) generated by Supabase Auth and execute:
INSERT INTO public.admin_users (id, name, email, role)
VALUES (
  'YOUR-USER-UUID-GOES-HERE',
  'Cartiae Rae',
  'admin@cartiaerae.com',
  'super_admin'
);

-- STEP C: Seed initial demo contact requests for development/preview
INSERT INTO public.contact_requests (id, name, email, phone, message, porosity, photo_attachment, status, date)
VALUES
(
  'CON-101',
  'Tiffany Adams',
  'tiff.adams@gmail.com',
  '+1 (555) 728-1923',
  'Hi Cartiae! I bought your organic oils last week, and I am struggling with severe breakage around my Crown region. How often should I apply the oil under my steam cap? Attached is a photo of my hair condition.',
  'Low Porosity 4C',
  'https://images.unsplash.com/photo-1595959183075-c1d0a5113cc3?auto=format&fit=crop&q=80&w=600',
  'Pending',
  '2026-06-11'
),
(
  'CON-102',
  'Nailah Vance',
  'nailah.v@outlook.com',
  '+1 (555) 381-8109',
  'My hair is extremely dry and absorbs water within five minutes, then gets flaky again. I attached a photo of my natural curls. Please advise if the Botanical formula will build up on my locs.',
  'High Porosity 4C',
  'https://images.unsplash.com/photo-1605980776566-0486c3ac7617?auto=format&fit=crop&q=80&w=600',
  'Pending',
  '2026-06-12'
);
*/
