/**
 * eBook Delivery Service
 *
 * ⚠️ SECURITY NOTICE — READ BEFORE RELYING ON THIS FILE
 * The demo link generator below uses `btoa` (base64). Base64 is ENCODING, not
 * encryption or signing: it is fully reversible and trivially forgeable in the
 * browser. The demo token is NOT secure and NOT tamper-proof. Do not use it to
 * gate access to real paid files in production.
 *
 * Real, tamper-proof delivery MUST be done server-side:
 *   1. Store eBook files in a PRIVATE bucket (Supabase Storage / S3) — never public.
 *   2. On a verified purchase (Stripe webhook `checkout.session.completed`),
 *      have a backend / serverless function generate a short-lived SIGNED URL
 *      (e.g. `supabase.storage.from('ebooks').createSignedUrl(path, expiresIn)`).
 *   3. Verify the purchase (order + email) before issuing any link.
 *   4. Email the signed URL to the buyer; let it expire.
 *
 * The `productionDelivery` interface below documents that server contract. The
 * `demo*` helpers keep the local sandbox functional but are clearly labeled.
 */

import { SecureDownloadToken } from '../types';

/**
 * Production integration contract — implement these on the server/serverless side.
 * The frontend should call these endpoints; it must never sign or verify tokens itself.
 */
export interface EbookDeliveryBackend {
  /**
   * Verify the buyer actually paid for this eBook, then return a short-lived
   * signed download URL generated by the storage provider.
   * Backend should: confirm the order/payment, confirm the email matches, then
   * create a signed URL (e.g. Supabase Storage `createSignedUrl`) with a TTL.
   */
  createSignedDownloadUrl(params: {
    orderId: string;
    email: string;
    ebookId: string;
    expiresInSeconds?: number;
  }): Promise<{ url: string; expiresAt: string } | { error: string }>;

  /**
   * Confirm a purchase exists for (orderId, email, ebookId) before delivery.
   */
  verifyPurchase(params: {
    orderId: string;
    email: string;
    ebookId: string;
  }): Promise<boolean>;
}

/**
 * Not implemented in the frontend on purpose. Wire this to a serverless function
 * (Netlify/Supabase Edge Function) that holds the storage service-role key.
 *
 * The live implementation of this contract is the Netlify function
 * `get-ebook-download` — call it through `fetchEbookDownloads` below.
 */
export const productionDelivery: EbookDeliveryBackend = {
  async createSignedDownloadUrl() {
    return { error: 'Signed download URLs must be generated by a backend. Not configured.' };
  },
  async verifyPurchase() {
    // No client-side purchase verification is trustworthy. Default to false.
    return false;
  },
};

// ── Production delivery client ─────────────────────────────────────────────

export interface EbookDownloadLink {
  ebookId: string;
  title: string;
  url: string;        // short-lived signed URL minted server-side
  expiresAt: string;  // ISO string
}

export interface EbookDownloadResult {
  /**
   * ready   — signed links are available
   * pending — order not recorded yet (Stripe webhook still in flight); retry
   * none    — the order contained no eBooks, nothing to deliver
   * error   — verification or signing failed; show `error` to the buyer
   */
  status: 'ready' | 'pending' | 'none' | 'error';
  downloads: EbookDownloadLink[];
  incomplete?: boolean;
  error?: string;
}

const DOWNLOAD_ENDPOINT = '/.netlify/functions/get-ebook-download';
const CONFIRM_ENDPOINT = '/.netlify/functions/confirm-order';

/**
 * Asks the backend to verify the payment with Stripe and record the order.
 *
 * This is what makes the store work without a Stripe webhook: the session id is
 * passed through, and the server retrieves that session from Stripe and records
 * it only if Stripe says it was paid. The browser cannot assert a payment.
 *
 * Best-effort by design — if it fails, the download call below still retries,
 * and reconcile-orders backfills anything missed.
 */
export async function confirmOrder(sessionId: string): Promise<boolean> {
  if (!sessionId) return false;
  try {
    const response = await fetch(CONFIRM_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sessionId }),
    });
    const data = await response.json();
    if (!response.ok) {
      console.warn('[ebookDelivery] confirmOrder failed:', data.error || response.status);
      return false;
    }
    return Boolean(data.recorded);
  } catch (err) {
    console.warn('[ebookDelivery] confirmOrder error:', err instanceof Error ? err.message : err);
    return false;
  }
}

const wait = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));

/**
 * Asks the backend for signed download links for a completed Stripe checkout.
 *
 * The buyer usually lands on the success page before Stripe has delivered the
 * `checkout.session.completed` webhook, so a 404 here means "not yet", not
 * "never" — we retry a few times with a growing delay before giving up.
 *
 * No token is generated or verified in the browser: the session id is merely
 * passed through, and the server decides whether anything was actually paid for.
 */
export async function fetchEbookDownloads(
  sessionId: string,
  email?: string,
  options: { retries?: number; retryDelayMs?: number } = {}
): Promise<EbookDownloadResult> {
  const retries = options.retries ?? 4;
  const retryDelayMs = options.retryDelayMs ?? 2000;

  if (!sessionId) {
    return { status: 'error', downloads: [], error: 'Missing checkout session reference.' };
  }

  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      const response = await fetch(DOWNLOAD_ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(email ? { sessionId, email } : { sessionId }),
      });

      const data = await response.json();

      if (response.ok) {
        const downloads: EbookDownloadLink[] = Array.isArray(data.downloads) ? data.downloads : [];
        return {
          status: downloads.length > 0 ? 'ready' : 'none',
          downloads,
          incomplete: Boolean(data.incomplete),
        };
      }

      // 404 + pending → the webhook has not landed yet. Wait and ask again.
      if (response.status === 404 && data.pending && attempt < retries) {
        await wait(retryDelayMs * (attempt + 1));
        continue;
      }

      return {
        status: response.status === 404 && data.pending ? 'pending' : 'error',
        downloads: [],
        error: data.error || `Server error (${response.status}).`,
      };
    } catch (err) {
      if (attempt < retries) {
        await wait(retryDelayMs * (attempt + 1));
        continue;
      }
      const message = err instanceof Error ? err.message : 'Unknown network error.';
      console.error('[ebookDelivery] fetchEbookDownloads error:', message);
      return {
        status: 'error',
        downloads: [],
        error: 'Could not reach the download service. Check your connection and try again.',
      };
    }
  }

  return { status: 'pending', downloads: [] };
}

export const ebookDeliveryService = {
  /**
   * DEMO ONLY — generates an UNSIGNED, forgeable base64 token so the local
   * sandbox can simulate an expiring link. Never treat this as secure.
   */
  generateDemoLink(orderId: string, email: string, ebookId: string, durationHours = 24): SecureDownloadToken {
    const expiresAt = new Date(Date.now() + durationHours * 60 * 60 * 1000).toISOString();

    // NOTE: base64 encoding only — anyone can decode/edit this. Demo purposes only.
    const demoToken = btoa(JSON.stringify({ orderId, email, ebookId, expiresAt, demo: true }));

    return { orderId, email, ebookId, expiresAt, token: demoToken };
  },

  /**
   * DEMO ONLY — decodes the demo token and checks the embedded (unauthenticated)
   * expiry. This only proves the string was well-formed and not past its date;
   * it proves NOTHING about payment or authenticity. Real verification is
   * server-side via `productionDelivery.verifyPurchase`.
   */
  verifyDemoLink(token: string): { valid: boolean; orderId?: string; ebookId?: string; error?: string } {
    try {
      const decoded = JSON.parse(atob(token)) as Omit<SecureDownloadToken, 'token'>;

      if (new Date() > new Date(decoded.expiresAt)) {
        return { valid: false, error: 'This demo download link has expired.' };
      }

      return { valid: true, orderId: decoded.orderId, ebookId: decoded.ebookId };
    } catch {
      return { valid: false, error: 'Malformed demo delivery token.' };
    }
  },

  /**
   * DEMO ONLY — logs a simulated confirmation email to the console. In production,
   * send the server-generated signed URL from a backend email service (SendGrid, SES).
   */
  sendDemoConfirmationEmail(customerName: string, customerEmail: string, orderId: string, downloadLinks: SecureDownloadToken[]): void {
    console.log(`
=========================================
[DEMO EMAIL SIMULATOR — not a real send]
TO: ${customerEmail} (${customerName})
SUBJECT: Your Cartiae Rae eBook Download (Order ${orderId})
=========================================
These are DEMO links (unsigned, local only). Production must email
short-lived signed URLs generated server-side after a verified purchase:

${downloadLinks.map(link => `- ${link.ebookId}: ${window.location.origin}/download?token=${link.token}`).join('\n')}

Support: orders@cartiaerae.com
=========================================
    `);
  }
};
