/**
 * eBook Delivery Service
 *
 * ⚠️ SECURITY NOTICE — READ BEFORE RELYING ON THIS FILE
 * The demo link generator below uses `btoa` (base64). Base64 is ENCODING, not
 * encryption or signing: it is fully reversible and trivially forgeable in the
 * browser. The demo token is NOT secure and NOT tamper-proof. Do not use it to
 * gate access to real paid files in production.
 *
 * Real, tamper-proof delivery MUST be done server-side:
 *   1. Store eBook files in a PRIVATE bucket (Supabase Storage / S3) — never public.
 *   2. On a verified purchase (Stripe webhook `checkout.session.completed`),
 *      have a backend / serverless function generate a short-lived SIGNED URL
 *      (e.g. `supabase.storage.from('ebooks').createSignedUrl(path, expiresIn)`).
 *   3. Verify the purchase (order + email) before issuing any link.
 *   4. Email the signed URL to the buyer; let it expire.
 *
 * The `productionDelivery` interface below documents that server contract. The
 * `demo*` helpers keep the local sandbox functional but are clearly labeled.
 */

import { SecureDownloadToken } from '../types';

/**
 * Production integration contract — implement these on the server/serverless side.
 * The frontend should call these endpoints; it must never sign or verify tokens itself.
 */
export interface EbookDeliveryBackend {
  /**
   * Verify the buyer actually paid for this eBook, then return a short-lived
   * signed download URL generated by the storage provider.
   * Backend should: confirm the order/payment, confirm the email matches, then
   * create a signed URL (e.g. Supabase Storage `createSignedUrl`) with a TTL.
   */
  createSignedDownloadUrl(params: {
    orderId: string;
    email: string;
    ebookId: string;
    expiresInSeconds?: number;
  }): Promise<{ url: string; expiresAt: string } | { error: string }>;

  /**
   * Confirm a purchase exists for (orderId, email, ebookId) before delivery.
   */
  verifyPurchase(params: {
    orderId: string;
    email: string;
    ebookId: string;
  }): Promise<boolean>;
}

/**
 * Not implemented in the frontend on purpose. Wire this to a serverless function
 * (Netlify/Supabase Edge Function) that holds the storage service-role key.
 */
export const productionDelivery: EbookDeliveryBackend = {
  async createSignedDownloadUrl() {
    return { error: 'Signed download URLs must be generated by a backend. Not configured.' };
  },
  async verifyPurchase() {
    // No client-side purchase verification is trustworthy. Default to false.
    return false;
  },
};

export const ebookDeliveryService = {
  /**
   * DEMO ONLY — generates an UNSIGNED, forgeable base64 token so the local
   * sandbox can simulate an expiring link. Never treat this as secure.
   */
  generateDemoLink(orderId: string, email: string, ebookId: string, durationHours = 24): SecureDownloadToken {
    const expiresAt = new Date(Date.now() + durationHours * 60 * 60 * 1000).toISOString();

    // NOTE: base64 encoding only — anyone can decode/edit this. Demo purposes only.
    const demoToken = btoa(JSON.stringify({ orderId, email, ebookId, expiresAt, demo: true }));

    return { orderId, email, ebookId, expiresAt, token: demoToken };
  },

  /**
   * DEMO ONLY — decodes the demo token and checks the embedded (unauthenticated)
   * expiry. This only proves the string was well-formed and not past its date;
   * it proves NOTHING about payment or authenticity. Real verification is
   * server-side via `productionDelivery.verifyPurchase`.
   */
  verifyDemoLink(token: string): { valid: boolean; orderId?: string; ebookId?: string; error?: string } {
    try {
      const decoded = JSON.parse(atob(token)) as Omit<SecureDownloadToken, 'token'>;

      if (new Date() > new Date(decoded.expiresAt)) {
        return { valid: false, error: 'This demo download link has expired.' };
      }

      return { valid: true, orderId: decoded.orderId, ebookId: decoded.ebookId };
    } catch {
      return { valid: false, error: 'Malformed demo delivery token.' };
    }
  },

  /**
   * DEMO ONLY — logs a simulated confirmation email to the console. In production,
   * send the server-generated signed URL from a backend email service (SendGrid, SES).
   */
  sendDemoConfirmationEmail(customerName: string, customerEmail: string, orderId: string, downloadLinks: SecureDownloadToken[]): void {
    console.log(`
=========================================
[DEMO EMAIL SIMULATOR — not a real send]
TO: ${customerEmail} (${customerName})
SUBJECT: Your Cartiae Rae eBook Download (Order ${orderId})
=========================================
These are DEMO links (unsigned, local only). Production must email
short-lived signed URLs generated server-side after a verified purchase:

${downloadLinks.map(link => `- ${link.ebookId}: ${window.location.origin}/download?token=${link.token}`).join('\n')}

Support: orders@cartiaerae.com
=========================================
    `);
  }
};
